apiVersion: v1
kind: Namespace
metadata:
  name: predscalens
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-inference-sa
  namespace: predscalens
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-inference-clusterrole
rules:
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ml-inference-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: ml-inference-sa
    namespace: predscalens
roleRef:
  kind: ClusterRole
  name: ml-inference-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference-server
  namespace: predscalens
  labels:
    app: ml-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference-server
  template:
    metadata:
      labels:
        app: ml-inference-server
    spec:
      serviceAccountName: ml-inference-sa
      containers:
        - name: inference-server
          image: ghcr.io/ilay9405/k8s-predictive-autoscaling-project:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
  namespace: predscalens
  labels:
    app: ml-inference-server
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ml-inference-server
