apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
  namespace: predscalens

  # locust python script setup.
data:
  locustfile.py: |
    import time
    import math
    from locust import HttpUser, task, LoadTestShape, constant

    # 1. The Victim (the pod that will experience a surge in traffic)
    class StressUser(HttpUser):
        wait_time = constant(1) # Send exactly 1 request per second per user

        @task
        def hit_endpoint(self):
            # A 2-second timeout so we don't freeze if the victim app crashes
            self.client.get("/", timeout=2)

     # 2. The Traffic Controller (Flash Sale pattern)
    class FlashSaleShape(LoadTestShape):
        def tick(self):
            run_time = self.get_run_time()
            
            # A 20 minute cycle (1200 seconds)
            # - First 15 minutes: Dead quiet (2 RPS)
            # - Next 2 minutes: Sudden ramp up to 25 RPS
            # - Last 3 minutes: Peak traffic holds at 25 RPS
            
            cycle_time = run_time % 1200
            
            if cycle_time < 900:  # The 15 minute quiet period
                return (2, 2)
            elif cycle_time < 1020:  # The 2 minute ramp up
                ramp_rps = int(2 + ((cycle_time - 900) / 120) * 23)
                return (ramp_rps, ramp_rps)
            else:  # The 3 minute peak sale
                return (25, 25)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: predscalens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
        - name: locust
          image: locustio/locust
          # Run headless (no UI) and target the internal Kubernetes DNS name!
          command: ["locust"]
          args:
            - "-f"
            - "/mnt/locust/locustfile.py"
            - "--headless"
            - "--host"
            - "http://stressor-app-service.default.svc.cluster.local"
          volumeMounts:
            - name: locust-script-vol
              mountPath: /mnt/locust
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
      volumes:
        - name: locust-script-vol
          configMap:
            name: locust-script
