name: Test and Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:
    name: Run Python Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from Github
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'